228 simulator integration updating export
massalabs/massa-sc-playground pull request #48
Opened 2022-11-04 14:16 UTC by 0xMazout

Some limitations :
- Files url are not very relevant 

At this moment according with PM. We don't need to spend more time on this.
Process is working : Uploading Config file, Send it to Playground Plugin API , Receive Two files

Needs : 
The model config file imported in the repo (execution_config.json) should be respected  
The playground Plugin API is needed to launch simulator and handle requests

To test : 
Clone Playground plugin API , Run it 
Run npx http-server on playground
Upload config file 
Simulate
Verify JSON file on urls or In the Playground plugin API repo

Links : 
API PLUGIN : https://github.com/massalabs/thyra-playground-plugin

2022-11-04 14:17 UTC, 0xMazout commented
This will not impact functionnality of Playground Web2.

2022-11-08 15:56 UTC, Thykof commented on module.js
> +// //update UI to hide Simulate and Upload Buttons if not connected to the plugin
```suggestion
// update UI to hide Simulate and Upload Buttons if not connected to the plugin
```

2022-11-08 16:29 UTC, 0xMazout commented on module.js
> +// //update UI to hide Simulate and Upload Buttons if not connected to the plugin
Done , Thanks for the review

2022-11-09 07:40 UTC, Trottoir requested changes

2022-11-09 07:40 UTC, Trottoir commented on execution_config.json
> +            {
It'd be better to have a file "ready to  play" instead of having the path `../massa-sc-examples/async-calls/build/main.wasm`

2022-11-09 07:40 UTC, Trottoir commented on execution_config.json
> +                    "address": "yvgsOkbC54I=",
All alls with yvgsOkbC54I= are not working as the contract is not deployed. We should maybe remove it before finding good strategy for : 
- Deploy ( executeSC)
- Call a function on a contract ( callSC )

2022-11-09 09:13 UTC, 0xMazout commented on execution_config.json
> +            {
I remove the file from the actual repo and send it to the repo playground plugin . Using another files working and specificaly using the context of the simulator and plugin

2022-11-09 16:39 UTC, Thykof requested changes

2022-11-09 16:39 UTC, Thykof commented on module.js
> +//TODO : Get Request to the simulator to get the legdger file
I don't understand this TODO, should we create a new issue?

2022-11-09 16:39 UTC, Thykof commented on module.js
> +                const Scfile = new File([outputs["deployer.wasm"]], "main.wasm", {
should we name this variable scFile?

2022-11-09 16:39 UTC, Thykof commented on module.js
> +                    //Todo handle the response, maybe the response will be asynchrone and take time to be ready
the response seems to be handle bellow, does this TODO up to date?

2022-11-09 17:17 UTC, 0xMazout commented on module.js
> +//TODO : Get Request to the simulator to get the legdger file
Done :)

2022-11-09 17:17 UTC, 0xMazout commented on module.js
> +                    //Todo handle the response, maybe the response will be asynchrone and take time to be ready
Deleted :)

2022-11-09 17:17 UTC, 0xMazout commented on module.js
> +                const Scfile = new File([outputs["deployer.wasm"]], "main.wasm", {
Done :)

2022-11-10 14:08 UTC, Trottoir approved these changes

2022-11-15 07:25 UTC, merged